//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunteerSystem.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int Id { get; set; }
        public string DriverId { get; set; }
        public string Plate { get; set; }
        public float CargoMaxWeight { get; set; }
        public string ModelDescription { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
