//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunteerSystem.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRequests
    {
        public int Id { get; set; }
        public int ResourceInfoId { get; set; }
        public float Count { get; set; }
        public string CustomerId { get; set; }
        public int WarehouseId { get; set; }
        public string DestinationState { get; set; }
        public string DestinationCity { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime DestinationTime { get; set; }
        public System.TimeSpan TransitTime { get; set; }
        public int Status { get; set; }
        public string DriverId { get; set; }
    
        public virtual ResourceInfoes ResourceInfoes { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
