//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolunteerSystem.Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceInfoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResourceInfoes()
        {
            this.ResWarehouses = new HashSet<ResWarehouses>();
            this.CustomerRequests = new HashSet<CustomerRequests>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public int ResType { get; set; }
        public int ResMeasure { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResWarehouses> ResWarehouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerRequests> CustomerRequests { get; set; }
    }
}
